### ISSUE TITLE
xlwings brake the installation on Ubuntu.

### ISSUE THREAD

**Issue by vinci1it2000** [JRCSTU/wltp#3]
The dependency with xlwings is breaking the installation of pandalone on Ubuntu because xlwings is supported for windows and OSX. Please make it optional.

**Comment by ankostis** [comment]
Fixed in `v0.1.0-alpha.0`.

Please @vinci1it2000 test, and close it if ok.

**Comment by ankostis** [comment]
@vinci1it2000 ping??

**Comment by ankostis** [comment]
Fixed in `v0.1.0-alpha.1` and checked in my VBox that is OK.
@vinci1it2000 please check and close.
